name: trenddrop-cron

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          EBAY_APP_ID: ${{ secrets.EBAY_APP_ID }}
          EPN_CAMPAIGN_ID: ${{ secrets.EPN_CAMPAIGN_ID }}
          CUSTOM_ID_PREFIX: ${{ secrets.CUSTOM_ID_PREFIX }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PYTHONPATH: ${{ github.workspace }}
        run: python -m bots.trenddrop

      - name: Commit updates
        run: |
          git config user.name "trenddrop-bot"
          git config user.email "bot@example.com"
          git add docs/data/products.json
          git commit -m "auto: refresh products" || echo "no changes"
          git push
